cursor #00a8cc
cursor_text_color #0a1b2a

foreground            #e2f1f8
background            #0a1b2a
background_opacity    0.15
dynamic_background_opacity yes
selection_foreground  #e2f1f8
selection_background  #1c3d5a
url_color             #00bbf9

color0   #07131f
color8   #1c3d5a
color1   #ff6b6b
color9   #ff8585
color2   #2ec4b6
color10  #4eedb0
color3   #ffe66d
color11  #fff099
color4   #1982c4
color12  #4ea8de
color5   #9b5de5
color13  #b5179e
color6   #00bbf9
color14  #90e0ef
color7   #f4f9f9
color15  #ffffff
