
name: origami-os

description: Un sistema operativo immutabile, modulare e dal design pulito basato su Universal Blue.


base-image: ghcr.io/ublue-os/fedora-silverblue
image-version: 44 


modules:
  - type: files
    files:
      - usr: /usr 

  - type: rpm-ostree
    install:
      - fastfetch 
      - git
      - curl
      - tmux

  - type: default-flatpaks
    notify: true
    install:
      - org.mozilla.firefox
